addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.6.1")
resolvers += Resolver.bintrayIvyRepo("scalameta", "sbt-plugins")
addSbtPlugin("com.lihaoyi" % "scalatex-sbt-plugin" % "0.3.8-pre")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC3")
addSbtPlugin("com.typesafe.sbt" % "sbt-ghpages" % "0.6.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-site" % "1.2.0")
